from io import open

from setuptools import find_packages, setup

# following src dir layout according to
# https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
version = "0.0.1"
setup(
    name="pytorch_examples",
    version=version,
    description="PyTorch examples",
    url="https://broadinstitute.github.io/pytorch_examples/",
    author="Kiran V Garimella",
    author_email="kiran@broadinstitute.org",
    license="BSD 3-Clause",
    long_description=open("README.rst").read(),
    install_requires=[
        'black',
        'bumpversion',
        'click',
        'click-log',
        'coverage',
        'cython',
        'flake8',
        'matplotlib',
        'mypy',
        'numpy',
        'ordered-set',
        'pandas',
        'pathos',
        'pydoc-markdown',
        'pylint',
        'pytest',
        'pytest-cov',
        'sphinx',
        'sphinx-rtd-theme',
        'tox',
        'torch',
        'torchvision',
        'tqdm',
        'twine',
        'wheel',
    ],
    tests_require=["coverage", "pytest"],
    python_requires=">=3.6",
    packages=find_packages("pytorch_examples"),
    package_dir={"": "pytorch_examples"},
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: BSD License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    entry_points={"console_scripts": ["pytorch_examples=pytorch_examples.__main__:cli"]},
    include_package_data=True,
)
